### ISSUE TITLE
Plasmid not existed in modpolish output

### ISSUE THREAD

**Issue by chen1i6c04** [ythuang0522/homopolish#48]
Hi

I try to correct my genome sequence with `modpolish`
But plasmid sequence not in result, because it could't be corrected ?

Thanks

**Comment by ythuang0522** [comment]
The bug has been fixed. Modpolish should output the unpolished short plasmids. Please pull the latest git version. Thanks.

**Comment by chen1i6c04** [comment]
I pull the latest program, but it still not output the plasmids

**Comment by Ted-Guo** [comment]
Hi
Thanks for your  response. We found the bug and fixed again. Please pull the latest git version. Thanks.

**Comment by chen1i6c04** [comment]
The latest version can output the plasmid sequence.
Thanks
